name = "MangalSuppMat"
uuid = "a356c4ae-9e6a-11e9-1f68-ad8e1e2e856f"
authors = ["Timoth√©e Poisot <timothee.poisot@umontreal.ca>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
Mangal = "b8b640a6-63d9-51e6-b784-5033db27bef2"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"
SimpleSDMLayers = "2c645270-77db-11e9-22c3-0f302a89c64c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
SimpleSDMLayers = "0.2"
